idf_component_register(SRCS "main_app.c"
                            "bsp/bsp_init.cpp"
                            "bsp/lvgl_adapter_init.c"
                            "bsp/bsp_audio.c"
                            "bsp/bsp_camera.c"
                            "bsp/bsp_wifi.c"
                            "rig/rig_mem.c"
                            "rig/rig_model.c"
                            "rig/rig_render.c"
                            "rig/rig_rig.c"
                            "rig/rig_lvgl.c"
                            "core/event_bus.c"
                            "core/memory_manager.c"
                            "core/app_config.c"
                            "app/app_state_machine.c"
                            "app/app_events.c"
                            "ui/ui_manager.c"
                            "ui/scr_home.c"
                            "ui/scr_chat.c"
                            "ui/themes/theme_manager.c"
                    INCLUDE_DIRS "."
                                "app"
                                "bsp"
                                "core"
                                "ui"
                                "ui/themes"
                                "rig"
                    EMBED_FILES "../assets/character_01.rigbin"
                    REQUIRES nvs_flash esp_event esp_netif lvgl__lvgl esp_timer
                    PRIV_REQUIRES espressif__esp32_p4_function_ev_board_noglib espressif__esp_lvgl_adapter espressif__esp_codec_dev espressif__esp_video espressif__esp_wifi_remote esp_wifi esp_mm)
